server:
  port: 8085  # Port on which the application will run
  servlet:
    context-path: /dvm  # Base path for all endpoints
logging:
  level:
    root: INFO  # Set the logging level for the root logger
spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    validation-query: SELECT 1
  jpa:
    hibernate:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.default_schema: ${DB_SCHEMA}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

